# Generated by Django 5.2.7 on 2025-11-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio y tipo de pantalla', max_length=100)),
                ('servicio', models.CharField(choices=[('netflix', 'Netflix'), ('disney', 'Disney+'), ('hbo_max', 'HBO Max'), ('jellyfin', 'Jellyfin'), ('prime_video', 'Prime Video'), ('youtube_premium', 'YouTube Premium'), ('vix', 'Vix Premium'), ('paramount', 'Paramount+'), ('plex', 'Plex'), ('canva', 'Canva Premium'), ('crunchyroll', 'Crunchyroll Premium'), ('spotify', 'Spotify Premium'), ('apple_tv', 'Apple TV+'), ('emby', 'Emby'), ('universal', 'Universal+'), ('shadowz', 'Shadowz'), ('telelatino', 'Telelatino'), ('gaia_tv', 'Gaia TV'), ('magis_tv', 'Magis TV'), ('directv_go', 'DirecTV Go'), ('rakuten_viki', 'Rakuten Viki'), ('iptv_smarters', 'IPTV Smarters Pro'), ('win_sports', 'Win Sports Online'), ('flujo', 'Flujo'), ('profenet_win', 'ProfeNet + Win+'), ('directv_win', 'DirecTV Go + Win'), ('claro_win', 'Claro Video + Win'), ('magis_win', 'Magis TV + Win'), ('telelatino_win', 'Telelatino + Win'), ('mlb_pass', 'MLB Pass'), ('nba_pass', 'NBA Pass'), ('wwe_network', 'WWE Network'), ('chatgpt_pro', 'ChatGPT Pro')], default='netflix', help_text='Tipo de servicio', max_length=50)),
                ('categoria', models.CharField(choices=[('streaming', 'Streaming'), ('deportes', 'Deportes'), ('musica', 'Música'), ('iptv', 'IPTV'), ('otros', 'Otros Servicios')], default='streaming', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Duración en días (27, 30, 33, 60, 90, 180, 365)')),
                ('tipo_pantalla', models.CharField(blank=True, default='', help_text='Ej: Original, Premium, Estándar, Platino, etc.', max_length=100)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad de cuentas disponibles')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta de Streaming',
                'verbose_name_plural': 'Cuentas de Streaming',
                'ordering': ['servicio', 'duracion_dias'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crud_app.order')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud_app.producto')),
            ],
        ),
    ]
